# Generated by Django 5.0.6 on 2024-07-24 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_email_alter_author_textbooks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='fib',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='likert',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='chapter',
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('note', 'Note'), ('example', 'Example'), ('subsection', 'Subsection'), ('image', 'Image'), ('video', 'Video'), ('mcq', 'MCQ'), ('fib', 'FIB'), ('likert', 'Likert')], max_length=16)),
                ('detail_id', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter')),
            ],
        ),
    ]
