# Generated by Django 5.0.6 on 2024-07-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_content_chapter_remove_content_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('note', 'Note'), ('example', 'Example'), ('subsection', 'Subsection'), ('image', 'Image'), ('video', 'Video')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fib',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fib',
            name='element_type',
            field=models.CharField(default='fib', max_length=16),
        ),
        migrations.AddField(
            model_name='likert',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likert',
            name='element_type',
            field=models.CharField(default='likert', max_length=16),
        ),
        migrations.AddField(
            model_name='mcq',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='element_type',
            field=models.CharField(default='mcq', max_length=16),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
