# Generated by Django 4.2.14 on 2024-08-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='chapter',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='app.chapter'),
            preserve_default=False,
        ),
    ]
