# Generated by Django 4.2.14 on 2024-08-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='fib',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
